version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "8081:27017"



  springboot:
    image: dsa05037/pnutour-springboot
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
    links:
      - mongodb


  fastapi:
    image: dsa05037/building-detecting-ai
    ports:
      - "8083:8000"
